apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  SIB_FROM_EMAIL: "mridulverma478@gmail.com"
  SIB_API_KEY: "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"
type: Opaque